# Generated by Django 5.2.13 on 2026-05-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_pet_apartment_friendly_pet_care_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_back_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_front_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rehomer_verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rehomer_verification_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rehomer_verification_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rehomer_verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
