# Generated by Django 5.2.13 on 2026-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0014_pet_medical_proof_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('wishlist_saved', 'Wishlist Saved'), ('chat_message', 'Chat Message'), ('application_submitted', 'Application Submitted'), ('application_withdrawn', 'Application Withdrawn'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('visit_proposed', 'Visit Proposed'), ('visit_agreed', 'Visit Agreed')], max_length=50),
        ),
    ]
