# Generated by Django 5.2.17 on 2026-08-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0015_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Trait Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português'), ('ru', 'Русский'), ('sw', 'Swahili')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone identifier (e.g., America/New_York)', max_length=50),
        ),
        migrations.CreateModel(
            name='BreedTraitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'Fish'), ('snake', 'Snake'), ('other', 'Other')], max_length=50)),
                ('breed', models.CharField(max_length=150)),
                ('data_source', models.CharField(choices=[('standard', 'Breed Standard/Registry'), ('community', 'Community Feedback'), ('adoption_data', 'Adoption Outcome Data'), ('manual', 'Manual Entry'), ('ml_trained', 'ML Model Trained')], default='standard', max_length=50)),
                ('trait_weights', models.JSONField(default=dict, help_text='Maps trait IDs to weights (0.0-1.0) indicating likelihood')),
                ('confidence_score', models.FloatField(default=0.5, help_text='How confident we are in this profile (0.0-1.0)')),
                ('sample_size', models.IntegerField(default=0, help_text='Number of pets/adoptions this profile is based on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Breed Trait Profiles',
                'ordering': ['species', 'breed'],
                'unique_together': {('species', 'breed')},
            },
        ),
        migrations.CreateModel(
            name='PersonalityTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('trait_type', models.CharField(choices=[('adopter', 'Adopter Only'), ('pet', 'Pet Only'), ('both', 'Both Adopter & Pet')], default='both', help_text='Whether this trait applies to adopters, pets, or both', max_length=20)),
                ('default_weight', models.FloatField(default=1.0, help_text='Default weight in ML matching (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traits', to='petapp.traitcategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
