# Generated by Django 5.2.17 on 2026-08-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0017_quizcategory_adopterquizresponse_quizquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed_trait_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='petapp.breedtraitprofile'),
        ),
        migrations.CreateModel(
            name='PetPersonalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_vector', models.JSONField(default=dict, help_text="Pet's personality traits and their weights (0.0-1.0)")),
                ('data_source', models.CharField(choices=[('breed_standard', 'Breed Standard'), ('rehomer_input', 'Rehomer Input'), ('adoption_history', 'Adoption History / ML'), ('hybrid', 'Hybrid (Multiple Sources)')], default='breed_standard', max_length=50)),
                ('confidence_score', models.FloatField(default=0.5, help_text='How confident we are in this profile (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_profiles', to='petapp.breedtraitprofile')),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality_profile', to='petapp.pet')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
