# Generated by Django 5.2.17 on 2026-08-29 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0018_pet_breed_trait_profile_petpersonalityprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('successful', 'Successful (Happy Adoption)'), ('unsuccessful', 'Unsuccessful (Returned/Failed)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Why was this adoption successful/unsuccessful?')),
                ('original_matching_score', models.FloatField(blank=True, help_text='The original compatibility score for this match', null=True)),
                ('was_used_for_training', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_outcome', to='petapp.adoptionapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingAlgorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this model version', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('cosine_similarity', 'Cosine Similarity (Vector-based)'), ('weighted_average', 'Weighted Average'), ('ml_trained', 'ML Model (Scikit-learn/PyTorch)'), ('hybrid', 'Hybrid Approach')], default='cosine_similarity', max_length=50)),
                ('model_weights', models.JSONField(default=dict, help_text='Algorithm-specific weights and parameters')),
                ('training_samples', models.IntegerField(default=0, help_text='Number of adoption outcomes used to train this model')),
                ('accuracy_on_training', models.FloatField(default=0.0, help_text='Model accuracy on training data (0-1)')),
                ('accuracy_on_validation', models.FloatField(default=0.0, help_text='Model accuracy on validation data (0-1)')),
                ('is_active', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='petapp.matchingalgorithmconfig')),
            ],
            options={
                'verbose_name_plural': 'Matching Algorithm Configs',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='MatchingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(help_text='Compatibility percentage (0-100%)')),
                ('trait_scores', models.JSONField(default=dict, help_text='Per-trait compatibility scores {trait_id: score}')),
                ('algorithm_version', models.IntegerField(default=1)),
                ('was_viewed', models.BooleanField(default=False)),
                ('was_liked', models.BooleanField(default=False)),
                ('application_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_score', to='petapp.adoptionapplication')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_scores', to='petapp.pet')),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'indexes': [models.Index(fields=['-compatibility_score'], name='petapp_matc_compati_245c2e_idx'), models.Index(fields=['adopter', '-compatibility_score'], name='petapp_matc_adopter_5ef972_idx'), models.Index(fields=['pet', '-compatibility_score'], name='petapp_matc_pet_id_91f7c7_idx')],
                'unique_together': {('adopter', 'pet')},
            },
        ),
    ]
