# Generated by Django 5.2.17 on 2026-09-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0020_rehomerreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("wishlist_saved", "Wishlist Saved"),
                    ("chat_message", "Chat Message"),
                    ("application_submitted", "Application Submitted"),
                    ("application_withdrawn", "Application Withdrawn"),
                    ("application_approved", "Application Approved"),
                    ("application_rejected", "Application Rejected"),
                    ("visit_proposed", "Visit Proposed"),
                    ("visit_agreed", "Visit Agreed"),
                    ("review_submitted", "Review Submitted"),
                ],
                max_length=50,
            ),
        ),
    ]
