# Generated by Django 5.2.17 on 2026-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petapp", "0021_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("pt", "Português"),
                    ("ru", "Русский"),
                    ("sw", "Swahili"),
                    ("zh", "中文"),
                ],
                default="en",
                max_length=10,
            ),
        ),
    ]
